name: MATLAB Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
        
      - name: Setup MATLAB
        run: |
          wget https://ssd.mathworks.com/supportfiles/ci/matlab-deps/v0/install.sh
          chmod +x install.sh
          sudo ./install.sh R2023a
          rm install.sh
          
          sudo apt-get install --no-install-recommends --no-upgrade --yes wget unzip ca-certificates
          
          wget https://www.mathworks.com/mpm/glnxa64/mpm
          chmod +x mpm
          ./mpm install --release=R2023b --release-status=Prerelease --products MATLAB Parallel_Computing_Toolbox
          
          wget https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v0/install.sh
          chmod +x install.sh
          ./install.sh
          
          echo "PATH=$PATH:/usr/share/matlab/bin:/opt/matlab-batch" >> $GITHUB_ENV
        
      - name: Run MATLAB command
        uses: matlab-actions/run-command@v1
        with:
          command: feature('HasDisplay') && usejava('swing')

      - name: Run MATLAB command
        uses: matlab-actions/run-command@v1
        with:
          command: usejava('swing')

      - name: Run MATLAB command
        uses: matlab-actions/run-command@v1
        with:
          command: feature('HasDisplay')
          
